debugging

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -29,11 +29,13 @@ jobs:
         # Add the OVH server to known_hosts to avoid host key verification failure
         echo "$OVH_SSH_HOST_KEY" >> ~/.ssh/known_hosts
 
-        # Start the SSH agent and add the key with the passphrase
+        # Start the SSH agent
         eval "$(ssh-agent -s)"
+        
+        # Add the SSH key with the passphrase
         echo "$SSH_PASSPHRASE" | tr -d '\n' | ssh-add ~/.ssh/id_ed25519
 
-        # Debug: List added SSH keys to ensure key is added
+        # Debug: List added SSH keys to ensure the key is added
         ssh-add -l || { echo "SSH key not added"; exit 1; }
 
         # Verify SSH connection with verbosity
@@ -43,4 +45,4 @@ jobs:
         echo "$OVH_PATH" > testfile.txt
 
         # Perform rsync deployment to the specific directory without delete option
-        rsync -avz -e "ssh -o StrictHostKeyChecking=yes -vvv" testfile.txt $OVH_USER@$OVH_HOST:$OVH_PATH || { echo "Rsync failed"; exit 1; }
+        rsync -avz -e "ssh -o StrictHostKeyChecking=yes -o IdentitiesOnly=yes -vvv" testfile.txt $OVH_USER@$OVH_HOST:$OVH_PATH || { echo "Rsync failed"; exit 1; }
